apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    app: app1
spec:
  containers:
    - name: web
      image: 240475/k8s-demo-app1:v1.0.0
      ports:
        - name: web
          containerPort: 80
          protocol: TCP